// <auto-generated />
using System;
using CentraalBureauVliegvaardigheden.LocalData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CentraalBureauVliegvaardigheden.LocalData.Migrations
{
    [DbContext(typeof(CBVContext))]
    partial class CBVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CentraalBureauVliegvaardigheden.Domain.Motor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Energie")
                        .HasColumnType("int");

                    b.Property<int>("Gewicht")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Motoren");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Energie = 150,
                            Gewicht = 150,
                            Naam = "Galaxy Class"
                        },
                        new
                        {
                            Id = 2,
                            Energie = 350,
                            Gewicht = 350,
                            Naam = "Intrepid Class"
                        },
                        new
                        {
                            Id = 3,
                            Energie = 200,
                            Gewicht = 200,
                            Naam = "Constellation Class"
                        });
                });

            modelBuilder.Entity("CentraalBureauVliegvaardigheden.Domain.Romp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Draagvermogen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rompen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Draagvermogen = "Interceptor",
                            Naam = "Zenith"
                        },
                        new
                        {
                            Id = 2,
                            Draagvermogen = "HeavyTank",
                            Naam = "Neptunus"
                        },
                        new
                        {
                            Id = 3,
                            Draagvermogen = "Tank",
                            Naam = "Katalyst"
                        },
                        new
                        {
                            Id = 4,
                            Draagvermogen = "MediumFighter",
                            Naam = "Racewing"
                        });
                });

            modelBuilder.Entity("CentraalBureauVliegvaardigheden.Domain.Schip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MotorId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RompId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MotorId");

                    b.HasIndex("RompId");

                    b.ToTable("Schepen");
                });

            modelBuilder.Entity("CentraalBureauVliegvaardigheden.Domain.Vleugel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Energie")
                        .HasColumnType("int");

                    b.Property<int>("Gewicht")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfHardpoints")
                        .HasColumnType("int");

                    b.Property<int?>("SchipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchipId");

                    b.ToTable("Vleugels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Energie = 0,
                            Gewicht = 275,
                            Naam = "Blade",
                            NumberOfHardpoints = 2
                        },
                        new
                        {
                            Id = 2,
                            Energie = 0,
                            Gewicht = 150,
                            Naam = "Horizon",
                            NumberOfHardpoints = 1
                        },
                        new
                        {
                            Id = 3,
                            Energie = 0,
                            Gewicht = 300,
                            Naam = "D-Fence",
                            NumberOfHardpoints = 3
                        },
                        new
                        {
                            Id = 4,
                            Energie = 15,
                            Gewicht = 250,
                            Naam = "O-Fence",
                            NumberOfHardpoints = 2
                        },
                        new
                        {
                            Id = 5,
                            Energie = 0,
                            Gewicht = 175,
                            Naam = "Raceing",
                            NumberOfHardpoints = 1
                        });
                });

            modelBuilder.Entity("CentraalBureauVliegvaardigheden.Domain.Wapen", b =>
                {
                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EnergieVerbruik")
                        .HasColumnType("int");

                    b.Property<int>("Gewicht")
                        .HasColumnType("int");

                    b.Property<string>("SchadeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VleugelId")
                        .HasColumnType("int");

                    b.HasKey("Naam");

                    b.HasIndex("VleugelId");

                    b.ToTable("Wapens");

                    b.HasData(
                        new
                        {
                            Naam = "Fury Cannon",
                            EnergieVerbruik = 52,
                            Gewicht = 76,
                            SchadeType = "Hitte"
                        },
                        new
                        {
                            Naam = "Crusher",
                            EnergieVerbruik = 56,
                            Gewicht = 89,
                            SchadeType = "Zwaartekracht"
                        },
                        new
                        {
                            Naam = "Flamethrower",
                            EnergieVerbruik = 74,
                            Gewicht = 30,
                            SchadeType = "Hitte"
                        },
                        new
                        {
                            Naam = "Freeze Ray",
                            EnergieVerbruik = 52,
                            Gewicht = 24,
                            SchadeType = "Bevriezing"
                        },
                        new
                        {
                            Naam = "Shockwave",
                            EnergieVerbruik = 47,
                            Gewicht = 105,
                            SchadeType = "Projectiel"
                        },
                        new
                        {
                            Naam = "Gauss Gun",
                            EnergieVerbruik = 52,
                            Gewicht = 110,
                            SchadeType = "Projectiel"
                        },
                        new
                        {
                            Naam = "Hailstorm",
                            EnergieVerbruik = 56,
                            Gewicht = 34,
                            SchadeType = "Bevriezing"
                        },
                        new
                        {
                            Naam = "Ice Barrage",
                            EnergieVerbruik = 41,
                            Gewicht = 35,
                            SchadeType = "Bevriezing"
                        },
                        new
                        {
                            Naam = "Imploder",
                            EnergieVerbruik = 43,
                            Gewicht = 270,
                            SchadeType = "Zwaartekracht"
                        },
                        new
                        {
                            Naam = "Levitator",
                            EnergieVerbruik = 56,
                            Gewicht = 59,
                            SchadeType = "Electrisch"
                        },
                        new
                        {
                            Naam = "Shredder",
                            EnergieVerbruik = 13,
                            Gewicht = 75,
                            SchadeType = "Electrisch"
                        },
                        new
                        {
                            Naam = "Tidal Wave",
                            EnergieVerbruik = 74,
                            Gewicht = 18,
                            SchadeType = "Electrisch"
                        },
                        new
                        {
                            Naam = "Volcano",
                            EnergieVerbruik = 10,
                            Gewicht = 80,
                            SchadeType = "Hitte"
                        },
                        new
                        {
                            Naam = "Nullifier",
                            EnergieVerbruik = 43,
                            Gewicht = 23,
                            SchadeType = "Zwaartekracht"
                        });
                });

            modelBuilder.Entity("CentraalBureauVliegvaardigheden.Domain.Schip", b =>
                {
                    b.HasOne("CentraalBureauVliegvaardigheden.Domain.Motor", "Motor")
                        .WithMany()
                        .HasForeignKey("MotorId");

                    b.HasOne("CentraalBureauVliegvaardigheden.Domain.Romp", "Romp")
                        .WithMany()
                        .HasForeignKey("RompId");

                    b.Navigation("Motor");

                    b.Navigation("Romp");
                });

            modelBuilder.Entity("CentraalBureauVliegvaardigheden.Domain.Vleugel", b =>
                {
                    b.HasOne("CentraalBureauVliegvaardigheden.Domain.Schip", null)
                        .WithMany("Vleugels")
                        .HasForeignKey("SchipId");
                });

            modelBuilder.Entity("CentraalBureauVliegvaardigheden.Domain.Wapen", b =>
                {
                    b.HasOne("CentraalBureauVliegvaardigheden.Domain.Vleugel", null)
                        .WithMany("Hardpoint")
                        .HasForeignKey("VleugelId");
                });

            modelBuilder.Entity("CentraalBureauVliegvaardigheden.Domain.Schip", b =>
                {
                    b.Navigation("Vleugels");
                });

            modelBuilder.Entity("CentraalBureauVliegvaardigheden.Domain.Vleugel", b =>
                {
                    b.Navigation("Hardpoint");
                });
#pragma warning restore 612, 618
        }
    }
}
